{
 "title": "ISP Monitoring",
 "description": "Monitor your ISP's Ping and DNS response times. Collect useful data like packet loss, uptime metrics on upstream services.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "urls", "query": { "query": "label_values(url)" } },
   { "name": "dns_servers", "query": { "query": "label_values(server)" } },
   { "name": "ping_url", "label": "ping_url", "query": { "query": "label_values(url)" } }
  ]
 },
 "panels": [
  { "title": "Ping Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$urls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "urls",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=\"$urls\"}",
     "legendFormat": "$url"
    }
   ]
  },
  { "title": "Upstream Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Ping Statistics for $ping_url",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"$ping_url\"}",
     "legendFormat": "min"
    },
    {
     "expr": "ping_average_response_ms{url=\"$ping_url\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"$ping_url\"}",
     "legendFormat": "max"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"$ping_url\"}",
     "legendFormat": "loss"
    }
   ]
  },
  {
   "title": "Avg Response Time for All urls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_average_response_ms{}", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Packet Loss % for All urls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ping_percent_packet_loss{}", "legendFormat": "{{url}}" }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$urls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "repeat": "urls",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg_over_time(ping_percent_packet_loss{url=\"$urls\"}[$__range])"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "DNS Response Time @$dns_servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "repeat": "dns_servers",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dns_query_query_time_ms{server=\"$dns_servers\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}