apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ispmonitor-ingress
spec:
  rules:
    - host: akorotkov.application.com
      http:
        paths:
          - path: /telegraf
            pathType: Prefix
            backend:
              service:
                name: ispmonitor
                port:
                  number: 9283
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
